// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzSxVmFs1oXXqiomCmbSNutPYBdt7lwPw',
    appId: '1:179182514244:web:4134997f4854a9d488cc11',
    messagingSenderId: '179182514244',
    projectId: 'ai-serenity',
    authDomain: 'ai-serenity.firebaseapp.com',
    storageBucket: 'ai-serenity.firebasestorage.app',
    measurementId: 'G-Z9E0JHKV0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlbV6rdHCe7mv547MFWiyDymVrzgjYPzE',
    appId: '1:179182514244:android:97c8f905b997ab7188cc11',
    messagingSenderId: '179182514244',
    projectId: 'ai-serenity',
    storageBucket: 'ai-serenity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoisZ2HcdZRPzWlUxpQQ7H-krj8ZN2G8',
    appId: '1:179182514244:ios:587d399ab640d0d388cc11',
    messagingSenderId: '179182514244',
    projectId: 'ai-serenity',
    storageBucket: 'ai-serenity.firebasestorage.app',
    iosBundleId: 'com.example.aiserenity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIoisZ2HcdZRPzWlUxpQQ7H-krj8ZN2G8',
    appId: '1:179182514244:ios:587d399ab640d0d388cc11',
    messagingSenderId: '179182514244',
    projectId: 'ai-serenity',
    storageBucket: 'ai-serenity.firebasestorage.app',
    iosBundleId: 'com.example.aiserenity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzSxVmFs1oXXqiomCmbSNutPYBdt7lwPw',
    appId: '1:179182514244:web:9aed4042298faf7688cc11',
    messagingSenderId: '179182514244',
    projectId: 'ai-serenity',
    authDomain: 'ai-serenity.firebaseapp.com',
    storageBucket: 'ai-serenity.firebasestorage.app',
    measurementId: 'G-202DTVBBHH',
  );

}